### ISSUE TITLE
Original average returns and t-statistics

### ISSUE THREAD

**Issue by shokru** [chenandrewy/flex-mining#12]
Dear Andrew, Alejandro and Tom, I was wondering: would it be possible to add the empirical results reported in the original papers (average returns & t-statistics) in the _SignalsTheoryChecked.csv_ file? Since you seem to use them in the paper, I guess you have them somewhere. This would save me a **lot** of time... and would likely be useful to others beyond me!
Thank you for your outstanding work, as usual!

**Comment by chenandrewy** [comment]
Thanks for the kind words Guillaume!  We could add the data, but the original paper results are found here: https://github.com/OpenSourceAP/CrossSection/blob/master/SignalDoc.csv and you should be able to dl and merge the files without much time.
