### ISSUE TITLE
Add a check for the number of stocks in each leg

### ISSUE THREAD

**Issue by chenandrewy** [chenandrewy/flex-mining#14]
@velikov-mihail helped me find that there's something up with the rdip/dlc strategy. It seems that this strategy usually only has one stock in the long leg: 

![image](https://github.com/chenandrewy/flex-mining/assets/65506481/5e74ee82-84db-4170-9df2-50a226ab3bbd)

This happens because the two variables rdip and dlc have lots of zeros, 

![image](https://github.com/chenandrewy/flex-mining/assets/65506481/a5f08f9e-ca6a-4224-adb1-738a3a2a21c4)

Anyway we should add a filter to make sure that each leg has a reasonable number of stocks.

**Comment by chenandrewy** [comment]
Here's a list of suspiciously high VW returns that @velikov-mihail found. FWIW, I could replicate the ridiculously high return of rdip/dlc. But there is, as you see above, only one stock in the long leg.

![image](https://github.com/chenandrewy/flex-mining/assets/65506481/e8e295cb-72d8-4976-9eb3-68bb2e3f3d7e)

**Comment by tomz23** [comment]
Addressed in https://github.com/chenandrewy/flex-mining/commit/f149158f16cb86a87fe97cd23a9147dde160c24d
